[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = """
      default-src 'self';
      connect-src 'self' https://api.emailjs.com https://www.google-analytics.com https://www.googletagmanager.com;
      script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
    """
    X-Frame-Options = "DENY"
    Cross-Origin-Opener-Policy = "same-origin"
